name: Website – Build and Deploy

on:
  push:
    branches:
      - prime
      - dev
    paths:
      - web/**
      - .github/workflows/website-build-and-deploy.yml

  workflow_dispatch:


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deployment Job
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Install Build Dependencies
        id: installbuilddependencies
        run: |
          corepack enable
          echo Using pnpm $(pnpm --version)
          pnpm install
        working-directory: web

      - name: Test
        id: test
        run: pnpm test
        working-directory: web

      - name: Build
        id: build
        run: pnpm run build-only
        working-directory: web

      - name: Deploy
        id: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          production_branch: prime
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_DUNE_034A1140F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: upload
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: web/dist/ # App source code path
          api_location: "" # Api source code path - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
